# .github/workflows/pre-commit.yml
name: Pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for pre-commit to check modified files

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Cache pre-commit environments
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-${{ runner.os }}-

    - name: Run pre-commit
      run: pre-commit run --all-files --show-diff-on-failure

    # Optional: Auto-fix pre-commit issues and push to PR
    # Uncomment the following lines if you want automatic fixes
    # - name: Auto-fix pre-commit issues
    #   if: failure() && github.event_name == 'pull_request'
    #   run: |
    #     pre-commit run --all-files || true
    #     git config --global user.name 'github-actions[bot]'
    #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    #     git add -A
    #     if git diff --staged --quiet; then
    #       echo "No changes to commit"
    #     else
    #       git commit -m "style: apply pre-commit fixes"
    #       git push
    #     fi
